target-version = "py38" # support python 3.8 and above

lint.unfixable = [
    "ERA", # do not autoremove commented out code
]
lint.select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "ERA", # flake8-eradicate/eradicate
    "I",   # isort
    "N",   # pep8-naming
    "PIE", # flake8-pie
    "PGH", # pygrep
    "RUF", # ruff checks
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",   # flake8
]
lint.ignore = [
    "B904", # use 'raise ... from err'
    "B905", # use explicit 'strict=' parameter with 'zip()'
    "N818", # Exception name should be named with an Error suffix
    "B008", # Do not perform calls in argument defaults
]

[format]
quote-style = "single" # use single quotes for non-triple-quoted strings
indent-style = "space" # use spaces for indentation
skip-magic-trailing-comma = false # do not skip adding a trailing comma when the last item is a magic comment
line-ending = "auto" # use the line ending of the first line of the file
docstring-code-format = false # do not format code in docstrings
docstring-code-line-length = "dynamic" # use the same line length as the rest of the file for code in docstrings
