name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  deploy:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.7.1
    - name: Config Build
      run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
    - name: Build package
      run: poetry build
    - name: Publish package
      run: poetry publish
